### ISSUE TITLE
Request: please add CardView too

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [baole/ForegroundView#2]

**Comment by Jawnnypoo** [comment]
CardView already supports `android:foreground` attributes

**Comment by AndroidDeveloperLB** [comment]
odd. i remember it didn't.

**Comment by baole** [comment]
To keep the library clean and dependency-less, ForegroundViewImpl is now public access. You can implement your own (Foreground)-CardView or other views using ForegroundViewImpl class. See [ForegroundButton](https://github.com/baole/ForegroundView/blob/master/library/src/main/java/com/anttek/foreground/widget/ForegroundButton.java) as an example
